version: "3.9"

services:
  pg-0:
    image: citusdata/citus
    labels: ["com.citusdata.role=Master"]
    environment:
      &AUTH
      POSTGRES_DB: "chat-db"
      POSTGRES_USER: "someuser"
      POSTGRES_PASSWORD: "p@ssw0rD"
      PGUSER: "someuser"
      PGPASSWORD: "p@ssw0rD"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      CITUS_HOST: "pg-0"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U someuser -d chat-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pg-worker:
    image: citusdata/citus
    labels: ["com.citusdata.role=Worker"]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
    depends_on:
      pg-0:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U someuser -d chat-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  shard-manager:
    image: citusdata/membership-manager:0.3.0
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on:
      pg-0:
        condition: service_healthy
    environment: *AUTH

  migrations-chat:
    build:
      context: ./chat
      dockerfile: ./migrate.Dockerfile
    environment:
      - POSTGRES_HOST=pg-0
      - POSTGRES_PORT=5432
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=p@ssw0rD
      - POSTGRES_DB=chat-db
    depends_on:
      pg-0:
        condition: service_healthy

  chat:
    build:
      context: ./chat
      dockerfile: ./Dockerfile
    ports:
      - "5060:5060"
    environment:
      - POSTGRES_HOST=pg-0
      - POSTGRES_PORT=5432
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=p@ssw0rD
      - POSTGRES_DB=chat-db
      - LOG_LEVEL=debug
      - ADDR=5060
      - JWT_KEY=kek
    depends_on:
      migrations-chat:
        condition: service_completed_successfully

volumes:
  healthcheck-volume: