version: "3.9"
services:
  db:
    image: bitnami/postgresql:14
    environment:
      POSTGRESQL_REPLICATION_MODE: "master"
      POSTGRESQL_REPLICATION_USER: "repl_user"
      POSTGRESQL_REPLICATION_PASSWORD: "repl_password"
      POSTGRES_DATABASE: "default-db"
      POSTGRES_USERNAME: "someuser"
      POSTGRES_PASSWORD: "p@ssw0rD"
    ports:
      - "5432:5432"
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U someuser -d default-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  db-slave:
    image: bitnami/postgresql:14
    environment:
      POSTGRESQL_REPLICATION_MODE: "slave"
      POSTGRESQL_REPLICATION_USER: "repl_user"
      POSTGRESQL_REPLICATION_PASSWORD: "repl_password"
      POSTGRESQL_MASTER_HOST: "db"
      POSTGRESQL_PASSWORD: "p@ssw0rD"
      POSTGRESQL_MASTER_PORT_NUMBER: "5432"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U someuser -d default-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  migrations:
    build:
      context: ./backend
      dockerfile: ./migrate.Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=p@ssw0rD
      - POSTGRES_DB=default-db
    depends_on:
      db-slave:
        condition: service_healthy
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=p@ssw0rD
      - POSTGRES_DB=default-db
      - LOG_LEVEL=debug
      - ADDR=5050
      - JWT_EXPIRATION=10
      - JWT_KEY=kek
    depends_on:
      migrations:
        condition: service_completed_successfully

volumes:
  postgresql_master_data: