version: "3.9"

services:
  pg-0:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
#      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
#      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=2
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=default-db
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d default-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pg-1:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=default-db
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d default-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pg-2:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_2_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=default-db
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d default-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgpool:
    image: bitnami/pgpool:latest
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432:0:pg-0:ALLOW_TO_FAILOVER,1:pg-1:5432:1:pg-1:ALLOW_TO_FAILOVER,2:pg-2:5432:1:pg-2:ALLOW_TO_FAILOVER
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
    depends_on:
      pg-0:
        condition: service_healthy
      pg-1:
        condition: service_healthy
      pg-2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: ./backend
      dockerfile: ./migrate.Dockerfile
    environment:
      - POSTGRES_HOST=pgpool
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=postgres
    depends_on:
      pgpool:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_HOST=pgpool
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=postgres
      - LOG_LEVEL=debug
      - ADDR=5050
      - JWT_EXPIRATION=10
      - JWT_KEY=kek
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=worker
      - FEEDWORKER_HOST=http://feed-worker:6050
    depends_on:
      migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50

  feed-worker:
    build:
      context: ./feed-worker
      dockerfile: ./Dockerfile
    ports:
      - "6050:6050"
    environment:
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=worker
      - LOG_LEVEL=debug
      - ADDR=6050
      - BACKEND_HOST=http://backend:5050
      - REDIS_HOSTS=redis:6379
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
  pg_2_data:
    driver: local