run:
  timeout: 30m
  tests: true
linters:
  disable-all: true
  enable:
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - exportloopref
    - typecheck
    - unconvert
    - whitespace
    - asciicheck
    - gocognit
    - godot
    - nestif
    - prealloc
    - testpackage
    - wsl
linters-settings:
  lll:
    line-length: 140
  funlen:
    lines: 80
    statements: 50
  goimports:
    local-prefixes: chat
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated
