// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "kek/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ServiceRepository is an autogenerated mock type for the ServiceRepository type
type ServiceRepository struct {
	mock.Mock
}

// CreateFriend provides a mock function with given fields: ctx, userID, friendID
func (_m *ServiceRepository) CreateFriend(ctx context.Context, userID uuid.UUID, friendID uuid.UUID) error {
	ret := _m.Called(ctx, userID, friendID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, friendID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePost provides a mock function with given fields: ctx, post
func (_m *ServiceRepository) CreatePost(ctx context.Context, post *domain.Post) error {
	ret := _m.Called(ctx, post)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Post) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *ServiceRepository) CreateUser(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFriend provides a mock function with given fields: ctx, userID, friendID
func (_m *ServiceRepository) DeleteFriend(ctx context.Context, userID uuid.UUID, friendID uuid.UUID) error {
	ret := _m.Called(ctx, userID, friendID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, friendID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePostByID provides a mock function with given fields: ctx, postID
func (_m *ServiceRepository) DeletePostByID(ctx context.Context, postID uuid.UUID) error {
	ret := _m.Called(ctx, postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFeedByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *ServiceRepository) GetFeedByUserID(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*domain.Post, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	var r0 []*domain.Post
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.Post); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFriendsWithUserID provides a mock function with given fields: ctx, userID
func (_m *ServiceRepository) GetFriendsWithUserID(ctx context.Context, userID uuid.UUID) ([]*domain.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 []*domain.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPostByID provides a mock function with given fields: ctx, postID
func (_m *ServiceRepository) GetPostByID(ctx context.Context, postID uuid.UUID) (*domain.Post, error) {
	ret := _m.Called(ctx, postID)

	var r0 *domain.Post
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Post); ok {
		r0 = rf(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPostsByAuthorID provides a mock function with given fields: ctx, authorID
func (_m *ServiceRepository) GetPostsByAuthorID(ctx context.Context, authorID uuid.UUID) ([]*domain.Post, error) {
	ret := _m.Called(ctx, authorID)

	var r0 []*domain.Post
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Post); ok {
		r0 = rf(ctx, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *ServiceRepository) GetUserByID(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersByPrefix provides a mock function with given fields: ctx, firstName, lastName
func (_m *ServiceRepository) GetUsersByPrefix(ctx context.Context, firstName string, lastName string) ([]*domain.User, error) {
	ret := _m.Called(ctx, firstName, lastName)

	var r0 []*domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*domain.User); ok {
		r0 = rf(ctx, firstName, lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetLastLoginUser provides a mock function with given fields: ctx, userID
func (_m *ServiceRepository) SetLastLoginUser(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePost provides a mock function with given fields: ctx, text, postID
func (_m *ServiceRepository) UpdatePost(ctx context.Context, text string, postID uuid.UUID) error {
	ret := _m.Called(ctx, text, postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = rf(ctx, text, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewServiceRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceRepository creates a new instance of ServiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceRepository(t mockConstructorTestingTNewServiceRepository) *ServiceRepository {
	mock := &ServiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
