CREATE TABLE IF NOT EXISTS posts
(
    id         UUID PRIMARY KEY,
    author_id UUID REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    text TEXT NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);